version: '3.9'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
      target: dev
    image: inctnce/grid-crypto-server
    volumes:
      - ./server:/usr/src/app/
    container_name: grid-crypto-server
    restart: always
    expose:
      - 4000
    ports:
      - 4000:4000
    command: npm run dev

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
      target: dev
    image: inctnce/grid-crypto-client
    volumes:
      - ./client:/usr/src/app/
    container_name: grid-crypto-client
    restart: always
    expose:
      - 3000
    ports:
      - 3000:3000
    command: npm run dev
  
  nginx:
    image: nginx:1.17.10
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
        - 80:80
        - 443:443
    depends_on:
        - server
        - client